### ISSUE TITLE
Using n to install node broke NPM

### ISSUE THREAD

**Issue by deremer** [tj/n#63]
I've been working on node 4.7 for a long time because that's all Heroku supported, but recently they announced support for other versions, so I was looking to upgrade node. Since I have production code working on 4.7, I need to swap between 4.7 and 6.13. 

n seems awesome and I'd love to use it. For running node, it works fine. But something happened when I installed it such that npm no longer works.

If I switch to n 0.4.7 and run 'npm install' for a module I get:

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module '../lib/npm.js'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at /usr/local/lib/node_modules/npm/bin/npm.js:24:11
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm.js:87:2)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at Array.<anonymous> (module.js:423:10)

If I switch to n 0.6.13 and run 'npm install' for a module I get:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: No such module
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/config-defs.js:5:21)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/ini.js:40:18)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)

Your help would be most appreciated as I can't seem to figure it out. Thanks!

**Comment by jessekinsman** [comment]
I agree with this issue it kind of makes this module useless

**Comment by noorzaie** [comment]
2+
