### ISSUE TITLE
Error with npm after updating from v0.10.33 to v4.x

### ISSUE THREAD

**Issue by matiasdecarli** [tj/n#310]
Before

```
➜  node --version
v0.10.33
➜  npm --version
1.4.28
```

After

```
➜  node --version
v4.1.0
➜  npm --version
1.4.28
```

And then, after a npm install, I get

```
➜  project git:(master) npm install
npm ERR! Error: Cannot find module '../utils/correct-mkdir.js'
npm ERR!     at Function.Module._resolveFilename (module.js:336:15)
npm ERR!     at Function.Module._load (module.js:286:25)
npm ERR!     at Module.require (module.js:365:17)
npm ERR!     at require (module.js:384:17)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/locker.js:9:20)
npm ERR!     at Module._compile (module.js:434:26)
npm ERR!     at Object.Module._extensions..js (module.js:452:10)
npm ERR!     at Module.load (module.js:355:32)
npm ERR!     at Function.Module._load (module.js:310:12)
npm ERR!     at Module.require (module.js:365:17)
npm ERR!     at require (module.js:384:17)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/matias/Workspace/project
npm ERR! node -v v4.1.0
npm ERR! npm -v 1.4.28
npm ERR! code MODULE_NOT_FOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/matias/Workspace/project/npm-debug.log
npm ERR! not ok code 0
```

Im using Yosemite. Is there any workarround for this?

**Comment by maxrimue** [comment]
What happens if you try `sudo npm -g install npm@latest`? If this command fails there most likely is something wrong with your npm installation

**Comment by matiasdecarli** [comment]
```
➜ project:(master) npm install -g npm@latest
npm ERR! Error: Cannot find module '../utils/correct-mkdir.js'
npm ERR!     at Function.Module._resolveFilename (module.js:336:15)
npm ERR!     at Function.Module._load (module.js:286:25)
npm ERR!     at Module.require (module.js:365:17)
npm ERR!     at require (module.js:384:17)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/locker.js:9:20)
npm ERR!     at Module._compile (module.js:434:26)
npm ERR!     at Object.Module._extensions..js (module.js:452:10)
npm ERR!     at Module.load (module.js:355:32)
npm ERR!     at Function.Module._load (module.js:310:12)
npm ERR!     at Module.require (module.js:365:17)
npm ERR!     at require (module.js:384:17)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "-g" "npm@latest"
npm ERR! cwd /Users/matias/Workspace/project
npm ERR! node -v v4.1.0
npm ERR! npm -v 1.4.28
npm ERR! code MODULE_NOT_FOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/matias/Workspace/murally-ansible/npm-debug.log
npm ERR! not ok code 0
```

**Comment by maxrimue** [comment]
Yeah so it's basically the same problem, it says that "correct-mkdir.js" is missing, I assume that's an internal module of npm, so we need to fix your npm installation. However, the npm version hasn't changed when you changed the Node.js version from 0.10.33 to 4.1.0, have you installed Node.js without n before? For example with homebrew?

**Comment by matiasdecarli** [comment]
> However, the npm version hasn't changed when you changed the Node.js version from 0.10.33 to 4.1.0...

Right, I also found this very strange.

> have you installed Node.js without n before? For example with homebrew?

Its probably but I dont remember to be honest

**Comment by maxrimue** [comment]
Well if you have homebrew and might have installed it that way, just do a `brew remove node`, if you haven't installed Node.js with homebrew this command will simply fail and not delete anything. If you however can't find out how you installed npm, it might be best to just remove npm from your system and install Node.js again using n, then it should work

**Comment by matiasdecarli** [comment]
Doing `brew ls` doesnt show node.

Im trying this on a Ubuntu and I have the very same behavior even when my mate, next to me, have this running ok on Yosemite

**Comment by maxrimue** [comment]
So you installed Node.js with n on a Ubuntu machine and it installed you an outdated version of npm? Or have you installed it sometime ago already too?

**Comment by matiasdecarli** [comment]
I've installed it sometime ago. Could this be the problem?

**Comment by maxrimue** [comment]
It could be, but I'm not really sure to be honest, as it's really weird that your problem is similar on two different platforms

**Comment by matiasdecarli** [comment]
I agree. I think I'll be reinstalling node on the ubuntu machine since its not my main machine and tell you what I've found

Thanks for your help @maxrimue

**Comment by maxrimue** [comment]
No problem @matiasdecarli, glad to help

**Comment by josephh** [comment]
@matiasdecarli I'm seeing the same thing, having used n to go from node 0.10.33 to 5.  Did you solve it?

**Comment by matiasdecarli** [comment]
@josephh no, I didn't solved it, I've just created another VM

**Comment by cdelauder** [comment]
My hacky solution to this is to treat switching versions as an install. This has allowed me to switch back and forth between node 4 and 0.10.36. It appears that n only adjusts your node version and not your npm  version, so instead of ```n``` and then selecting the desired installed node version, I specifiy ```n 4.2.0``` or ```n 0.10.36``` and I no longer have this problem.

**Comment by shadowspawn** [comment]
This has probably been fixed by #470

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
